<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2VMd7p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2VMd7p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2VMd7p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2VMd7p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2VMd7p\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2VMd7p',
    'container.build_id' => 'e961fbd0',
    'container.build_time' => 1643674946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2VMd7p');
