<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ZDumGZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ZDumGZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6ZDumGZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6ZDumGZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6ZDumGZ\App_KernelDevDebugContainer([
    'container.build_hash' => '6ZDumGZ',
    'container.build_id' => '5ff89514',
    'container.build_time' => 1643667941,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ZDumGZ');
