<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ad extends \App\Entity\Ad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'postalCode', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'seller', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'buyer', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'review', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'messages', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'medias', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'tags', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'currency', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'validationCode'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'postalCode', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'seller', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'buyer', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'review', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'messages', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'medias', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'tags', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'currency', '' . "\0" . 'App\\Entity\\Ad' . "\0" . 'validationCode'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $price): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode(string $postalCode): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postalCode]);

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $status): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller', []);

        return parent::getSeller();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller(?\App\Entity\User $seller): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller', [$seller]);

        return parent::setSeller($seller);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyer(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyer', []);

        return parent::getBuyer();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyer(?\App\Entity\User $buyer): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyer', [$buyer]);

        return parent::setBuyer($buyer);
    }

    /**
     * {@inheritDoc}
     */
    public function getReview(): ?\App\Entity\Review
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReview', []);

        return parent::getReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setReview(?\App\Entity\Review $review): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReview', [$review]);

        return parent::setReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', []);

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage(\App\Entity\Message $message): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', [$message]);

        return parent::addMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessage(\App\Entity\Message $message): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessage', [$message]);

        return parent::removeMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', []);

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\App\Entity\Media $media): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', [$media]);

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\App\Entity\Media $media): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', [$media]);

        return parent::removeMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\App\Entity\Tag $tag): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', [$tag]);

        return parent::addTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\App\Entity\Tag $tag): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', [$tag]);

        return parent::removeTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(string $currency): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationCode', []);

        return parent::getValidationCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidationCode(string $validationCode): \App\Entity\Ad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidationCode', [$validationCode]);

        return parent::setValidationCode($validationCode);
    }

}
